task:
  name: Build Flutter App
  docker:
    - image: cirrusci/flutter:stable
  script:
    - flutter pub get
    - flutter pub run build_runner build --delete-conflicting-outputs
    - flutter build apk --release
  artifacts:
    - build/app/outputs/flutter-apk/app-release.apk
